#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016 Konstantin Gredeskoul
# Project Pullulant™
# https://github.com/kigster/pullulant/
#
# Distributed under MIT License
#
# FEATURE: Web Depdencies
#_______________________________________________________________________________
#
[[ -n "${bash_it_plugins}" ]] || bash_it_plugins="nginx"
[[ -n "${brew_packages}" ]]   || brew_packages=" elasticsearch haproxy nginx redis solr rabbitmq "
