#!/usr/bin/env bash
#
#        File: alfred-install
#     Project: Pullulant — Completion
#              © 2015—2016 Konstantin Gredeskoul, all rights reserved.
#     License: MIT
#   Home Page: https://github.com/kigster/pullulant
#
#_______________________________________________________________________________

function alfred-install() {
  [[ -d /Applications/Alfred\ 3.app ]] || { 
    [[ -z "$(brew cask list -1 | grep alfred)" ]] && {
      run "brew cask install alfred"
    }
  }
  run "mkdir -p $alfred_dir"
  run "pushd $alfred_dir"
  for plugin in $alfred_plugins; do
    run "curl -s -L -O -w %{filename_effective} $plugin"
  done
  run "open ${alfred_dir}"
  run "popd"
}
