#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016-2021 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#

function atom-snapshot {
  last_command_status=0
  if [ -z "$apm" ]; then
    run "printf \"${bldylw} It looks like you don't have *apm* installed – it comes with Atom.\n\""
    run "printf \"${bldwht} Please make sure you have the latest Atom installed, then re-run\n"
  else
    run "apm list --installed --bare > ${HOME}/.atom/packages.txt # show-stdout "
  fi
  run "cp -p ${HOME}/.atom/{*.[jc]son,*.txt,*.md,.*.json,*.coffee,*.less} ${rsync_atom_dir}/ 2>/dev/null # show-stdout"
  return $last_command_status
}