#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016 Konstantin Gredeskoul
# Project Pullulant™
# https://github.com/kigster/pullulant/
#
# Distributed under MIT License
#_______________________________________________________________________________

# This function returns list of aliases, plugins and completions in bash-it,
# whose name or description matches one of the search terms provided as arguments.
#
# Usage:
#   ❯ source helpers/bashitlookup
#   ❯ bash-it-lookup <search term1> <term2> <term3> ....
# Example:
#   ❯ source helpers/bash-it-lookup
#   ❯ bash-it-lookup ruby rbenv rvm gem rake
#  aliases: bundler
#  plugins: chruby,chruby-auto,rbenv,ruby,rvm
#  completions: gem,rake
#

function bash-it-lookup() {
  local terms=($@)
  declare -a types=(aliases plugins completions)
  for type in "${types[@]}" ; do
    declare -a matches=()
    for term in "${terms[@]}"; do
      local term_match=($(bash-it show ${type} | grep -i ${term} | cut -d ' ' -f 1  | tr '\n' ' '))
      [[ "${#term_match[@]}" -gt 0 ]] && {
        matches=(${matches[@]} ${term_match[@]})
      }
    done
    if [[ "${#matches[*]}" -gt 0 ]] ; then
      printf "${type}: %s\n" $(echo -n ${matches[*]} | tr ' ' '\n' | sort | uniq | tr '\n' ', ' | sed 's/,$//g')
    fi
    unset matches
  done
}
q
