#!/usr/bin/env bash
export brew_has_been_upgraded=
function brew-upgrade {
  if [ -z "$(which brew)" ]; then
    run "echo 'Brew is not installed!'"
    status=200
    return
  fi
  if [ ! -z "$skip_brew_upgrade" ]; then
    run "echo 'Skipping brew upgrade...'"
    status=0
    return
  fi
  if [ -z "$brew_has_been_upgraded" ]; then
    run "printf '${bldylw}Upgrading every homebrew formula and cask, please wait while its fermenting...${txtrst}\n'"
    run "brew upgrade --verbose | grep Pouring; true # show-stdout"
    export brew_has_been_upgraded=yes
  fi
}
