#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016-2021 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________

function brew-wipe {
  brew=`which brew`
  export opts_quiet=true
  if [ ! -z "${brew}" ]; then
    printf "Homebrew is installed, version $(brew --version)\n"
    printf "${bldylw}Let's wipe it completely!${txtrst}\n\n"
    run 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" -- -f'
    run "sudo mv /Library/Cache/Homebrew /Library/Cache/Homebrew.${const_timestamp}" "ignore_error"
    run "sudo mv /opt/homebrew-cask /opt/homebrew-cask.${const_timestamp}" "ignore_error"
  else
    cmd='printf "Homebrew is not installed...\n\n"'
    run "$cmd"
  fi
}
