#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________

export brew_has_been_updated=
function brew-update {
  if [ -z "$brew_has_been_updated" ]; then
    run "printf '${bldgrn}Updating your Homebrew, please wait while its brewing...${txtrst}\n'"
    run "brew update --rebase # show-stdout"
    export brew_has_been_updated=yes
  fi
}
