#!/usr/bin/env bash
# This is a minimal home brew install in order to get a recent working ruby
# so that we can run sprout-wrap that contains the rest of the install.
#
# Relies on functions in pullulant/helpers/commands
#
function brew-wipe {
  brew=`which brew`
  export verbose=true
  if [ ! -z "${brew}" ]; then
    printf "Homebrew is installed, version $(brew --version)\n"
    printf "${bldylw}Let's wipe it completely!${txtrst}\n\n"
    run 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" -- -f'
    run "sudo mv /Library/Cache/Homebrew /Library/Cache/Homebrew.${timestamp}; true"
    run "sudo mv /opt/homebrew-cask /opt/homebrew-cask.${timestamp}; true"
  else
    cmd='printf "Homebrew is not installed...\n\n"'
    run "$cmd"
  fi
}
