#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016-2021 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#

function iterm-colorschemes {
  last_command_status=0
  local install_home="$pu_cfg/iterm2"
  local zipfile="$install_home/iterm2-themes.zip"

  if [[ ! -d "$install_home" ]]; then
    run "mkdir -p ${pu_cfg}"
    run "mkdir -p ${install_home}"
  fi

  run "cd $install_home && curl -LO https://github.com/mbadolato/iTerm2-Color-Schemes/zipball/master"
  run "cd $install_home && mv master $zipfile && unzip $zipfile"

  if [[ $opts_install_only_selected_themes == "yes" ]]; then
    for theme in $iterm_themes; do
      install_theme $install_home $theme
    done
  else
    run "find $install_home -name '*.itermcolors' -exec open {} \;"
  fi

  # if there is no bash process associated with an iTerm, we can nuke iTerm.
  (sleep 5 && open /Applications/iTerm.app) &
  sudo kill -9 $(ps -ef | grep [i]Term | awk '{print $2}')

  return 0
}


function install_theme {
  install_dir=$1
  theme=$2
  run "find $install_dir/mba*/schemes -name '$theme*' -exec open {} \;"
}
