#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#

function install_iterm_themes {
  last_command_status=0
  local install_home="$pu_cfg/iterm2"
  local zipfile="$install_home/iterm2-themes.zip"
  if [[ ! -d "$install_home" ]]; then
    run "mkdir -p ${pu_cfg}"
    run "mkdir -p ${install_home}"
    run "cd $install_home && curl -LO https://github.com/mbadolato/iTerm2-Color-Schemes/zipball/master"
    if [[ "$(ls -al $install_home/master | awk '{print $5}')" == "$(ls -al $zipfile | awk '{print $5}')" ]]; then
      rm -f "${install_home}/master"
    else
      run "cd $install_home && mv master $zipfile && unzip $zipfile"
    fi
  fi

  if [[ $opts_install_only_selected_themes == "yes" ]]; then
    for theme in $iterm_themes; do
      install_theme $install_home $theme
    done
  else
    run "find $install_home -name '*.itermcolors' -exec open {} \;"
  fi

  # if there is no bash process associated with an iTerm, we can nuke iTerm.
  is_iterm=$(for pid in $(ps -ef | grep bash | awk '{print $3}' | sort | uniq ); do ps -p $pid; done | grep iTerm)
  [[ -z "${is_iterm}" ]] && kill -9 $(ps -ef | grep [i]Term | awk '{print $2}')
  return 0
}


function install_theme {
  install_dir=$1
  theme=$2
  run "find $install_dir/mba*/schemes -name '$theme*' -exec open {} \;"
}
