#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________

function postgres-wipe {
  postgres-stop
  run "brew uninstall ${opts_verbose} postgres --force" "ignore_error"
  return 0
}
