#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016-2021 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________

function postgres-start {
  [[ -n "$(postgres-master-pid)" ]] && {
    run "printf '${bldylw}Warning: ${bldwht}PostgreSQL is already running\n'"
    return
  }

  run "brew services start postgresql"
  last_command_status=0
  return $last_command_status
}
