#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016-2021 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________

function postgres-stop {
  [[ -z "$(postgres-master-pid)" ]] && {
    run "printf '${bldylw}Warning: ${bldwht}PostgreSQL is already not running\n'"
    return
  }
  # brew-update
  run "brew services stop postgresql"
  run "sleep 1"
  attempt=0
  while [ -n "$(postgres-master-pid)" -a $attempt -lt 2 ]; do
    run "echo 'Detected that PostgreSQL is still running'"
    pid=$(postgres-master-pid)
    [[ $attempt -eq 0 ]] && run "sudo pkill postgres"
    [[ $attempt -eq 1 ]] && run "sudo pkill -9 postgres"
    attempt=$(($attempt + 1))
    run "echo 'Waiting for postgres to stop...'"
    run "sleep 1"
  done
  [[ -z "$(postgres-master-pid)" ]] && run "printf '${bldgrn}Success. ${bldwht}PostgreSQL is not running\n'"
  return 0
}
