#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016-2021 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________

sudo-disable() {
  if [[ ${sudoers_enabled} == true && ${skip_sudo_disable} == false ]]; then
    pu-print-section-header "${txtblk}${bakylw}" "Disabling sudo without a password... "
    run "sudo rm -f /private/etc/sudoers.d/${USER} # hide-command"
  fi
  unset sudoers_enabled
}
