#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________

sudoers_dir="/private/etc/sudoers.d"
export sudoers_enabled=

sudo-enable() {
  run "[[ -d ${sudoers_dir} ]] || sudo mkdir -p ${sudoers_dir}"
  [[ -s ${sudoers_dir}/${USER} ]] || {
    echo 'kig ALL=(ALL) NOPASSWD: ALL' | sudo tee -a ${sudoers_dir}/kig
    export sudoers_enabled=true
  }
}
