#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#
function install_zsh {
  [[ -z "$opts_change_shell_to_zsh" ]] && {
    run "printf '${bldgrn}skipping ZSH installation due to -Z flag not set.${txtrst}\n'"
    return 0
  }

  zsh-permissions

  rsync_opts=""

  [[ -n "${opts_force}" ]] && run "rm -rf ${HOME}/.oh-my-zsh ${HOME}/.zsh* ${HOME}/.zcomp*"

  oh-my-zsh-installer

  [[ -z "$(echo $SHELL | grep zsh)" && -n "${opts_change_shell_to_zsh}" ]] && run "sudo chsh -s /usr/local/bin/zsh ${USER}"

  run "rsync ${opts_verbose} ${opts_rsync_backup} -a ${zsh_rsync_home_dir}.zshrc ${HOME}/"
  run "rsync ${opts_verbose} ${opts_rsync_backup} -a ${zsh_rsync_home_dir}.select-prompt ${HOME}/"
  run "rsync ${opts_verbose} ${opts_rsync_backup} -a ${zsh_rsync_home_dir}.oh-my-zsh/ ${HOME}/.oh-my-zsh"

  rc=${HOME}/.zshrc
  [[ -f "$rc" ]] || touch $rc
  [[ -n "$(grep THEME=\"${var_zsh_theme}\" $rc)" ]]  || run "sed -i.bak -e 's/ZSH_THEME=\".*\"/ZSH_THEME=\"${var_zsh_theme}\"/g' $rc"
  [[ -n "$(grep PU_HOME $rc)" ]] || run "echo 'PU_HOME=${pu_home}; PATH=\$PATH:\${PU_HOME}; unalias pu' >> $rc "
}

function oh-my-zsh-installer {
  [[ -z "$(grep -e /zsh$ /etc/shells)" ]] && brew_install "zsh"
  [[ -z "$ZSH" ]]                         && ZSH=${HOME}/.oh-my-zsh
  [[ -z "$(which git)" ]]                 && brew_install "git"
  if [ -d "$ZSH" ]; then
    run "printf \"${bldylw}Looks like your oh-my-zsh is already installed\n\""
    run "printf \"${txtrst}You'll need to remove $ZSH if you want to re-install\n\""
  else
    run "env git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git $ZSH"
  fi
}

function zsh-permissions {
  run "mkdir -p /usr/local/share/zsh && chmod -R 750 /usr/local/share/zsh"
  run "mkdir -p /usr/local/Cellar/zsh && chmod -R 750 /usr/local/Cellar/zsh"
}
