#!/usr/bin/env ruby

site 'https://supermarket.getchef.com/api/v1'

cookbook 'sprout-git',
  :github => 'pivotal-sprout/sprout-git'

cookbook 'sprout-homebrew',
  :github => 'pivotal-sprout/sprout-homebrew.git'

cookbook 'homebrew',
  :github => 'chef-cookbooks/homebrew'

cookbook 'sprout-pyenv',
  :github => 'kigster/sprout-pyenv'

cookbook 'sprout-base',
  :github => 'pivotal-sprout/sprout-base'

cookbook 'sprout-osx-apps',
  :github => 'pivotal-sprout/sprout-osx-apps'

cookbook 'sprout-osx-settings',
  :github => 'pivotal-sprout/sprout-osx-settings'

cookbook 'osx',
  :github => 'pivotal-sprout/osx'

cookbook 'sprout-terminal',
  :github => 'pivotal-sprout/sprout-terminal'

cookbook 'sprout-ssh',
  :github => 'pivotal-sprout/sprout-ssh'
