#!/usr/bin/env bash
bash_it_aliases+=" docker docker-compose "
bash_it_plugins+=" docker docker-machine "
bash_it_completions+=" docker "
brew_packages+=" go "
brew_casks+=" dockertoolbox "
rbenv_ruby_versions+=("2.3.0")
