#!/usr/bin/env bash
#
# (c) 2015-2016 pullulant Inc.
# Author: Konstantin Gredeskoul, kig@reinvent.one
# http://reinvent.one
#

function load_module {
  submodules=$(echo `$1`)
  for submodule in $submodules; do
    source ${2}/$submodule
  done
}

function init {
  load_module "ls -1 lib/*" "."

  load_module "ls -1 $helpers_dir" $helpers_dir
  export helpers=${submodules}

  load_module "ls -1 $modules_dir" $modules_dir
  export installers=$(echo $submodules | sed -E 's/[0-9]+_//g')
  export status=0
}

init

function main {
  # loop over installers, and if either passed as an argument or no arguments
  #" at all – run it."
  [[ -z "${runners}" ]] || on_start

  local runners_started=0
  local runners_completed=0
  for runner in $runners; do
    export runners_started=$((runners_started + 1))

    [[ $runners_started -gt 1 ]] || greet

    section ${runner}

    export status=
    eval ${runner}
    status=${status:-1}

    if [ ${status:-1} -ne 0 ]; then
      printf "${bldred}Non-zero status ${status} from '${runner}' runner :( ...\n${txtrst}"
      abort $status
    fi

    runners_completed=$(($runners_completed + 1))
  done

  if [ $status -eq 0 -a $runners_completed -gt 0 ]; then
    finish
  elif [ $status -eq 0 -a $runners_completed -eq 0 ]; then
    printf "${bldylw}\nNo runners were specified.${txtrst}\nPlease run $0 -h for help.\n"
    finish
  else
    abort $status
  fi
}

#______________________________________________________________________________
#

while getopts "ar:SBLRqnvlh" opt; do
  case $opt in
    a)
        export runners=${installers}          ;;
    # this is left for legacy only, -r is the new flag that should be used.
    i)
        printf "${bldred}Whoops! The -i flag is no longer used, please use -r (for 'runner').\n${txtrst}"
        abort 125                            ;;
    r)
        if [ -z "$runners" ]; then
          export runners="$OPTARG"
        else
          export runners="$runners $OPTARG"
        fi                                    ;;
    h)
        greet; help; finish;                  ;;
    q)
        export opts_quiet=                    ;;
    n)
        export opts_dryrun=yes                ;;
    v)
        export opts_verbose=" -v ";           ;;
    l)
        installer_info; finish;               ;;
    S)
        export opts_skip_sprout_wrap=yes      ;;
    B)
        export opts_skip_brew_upgrade=yes     ;;
    L)
        export opts_brew_force_link=yes       ;;
    R)
        export opts_brew_force_reinstall=yes  ;;
    \?)
        help
        printf "${bakred}ERROR: $* is an invalid option :( ${txtrst}\n" >&2
        abort 126
        ;;
    :)
        printf "${bakred}ERROR: option -$opt requires an argument ${txtrst}\n" >&2
        abort 127
        ;;
  esac
done


main $*
