#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016 Konstantin Gredeskoul
# Project Pullulant™
# https://github.com/kigster/pullulant/
#
# Distributed under MIT License
#_______________________________________________________________________________
#
[[ -n "${bash_it_plugins}" ]]     || bash_it_plugins=""
[[ -n "${bash_it_aliases}" ]]     || bash_it_aliases=""
[[ -n "${bash_it_completions}" ]] || bash_it_completions=""


# List of Brew Formulas to install and l`ink
[[ -n "${brew_packages}" ]] || brew_packages="
  cloc
"

[[ -n "${brew_packages_to_link_after_install}" ]] || brew_packages_to_link_after_install=""

[[ -n "${brew_casks}" ]] || brew_casks="
  dash
"

[[ -n "${brew_relink_packages}" ]] || brew_relink_packages="
"
# these hosts will be added to /etc/hosts as 127.0.0.1
# eg. local.mydomain.com
[[ -n "${local_hosts}" ]] || local_hosts=""

# This is the ruby/python version that will be installed using rbenv
# the first one in the list will be set as the default. At least one
# is required to keep going with SproutWrap.
[[ -n "${rbenv_ruby_versions}" ]]   || rbenv_ruby_versions=("2.3.0")
[[ -n "${pyenv_python_versions}" ]] || pyenv_python_versions=()

# These define optional modules for node, python and ruby. Note that
# these are installed as part of the corresponding install process.
# So python would only install if `python_install` is run.

[[ -n "${nodejs_modules}" ]] || nodejs_modules="
  bower
"
[[ -n "${python_modules}" ]] || python_modules="
  thefuck
"
[[ -n "${ruby_modules}" ]]   || ruby_modules="
  bundler
  warp-dir
"

[[ -n "${alfred_plugins}" ]] || alfred_plugins="
"

[[ -n "${iterm_themes}" ]]   || iterm_themes=""
