#!/usr/bin/env bash

[[ -n "${bash_it_plugins}" ]] || bash_it_plugins="
  ruby
  rbenv
  rvm
"

[[ -n "${bash_it_aliases}" ]] || bash_it_aliases="
  bundler
  rails
"

[[ -n "${bash_it_completions}" ]] || bash_it_completions="
  rake
  capistrano
  bundler
  gem
"

brew_packages+="
  libiconv
  libmemcached
  libxml2
  libxslt
  libzip
  openssl
  pcre
  qt
  rbenv
  ruby-build
  wget
  zlib
"

brew_casks+="
  rubymine
  webstorm
  atom-beta
  textmate
"

brew_relink_packages+="
  libiconv
  libxml2
  libxslt
  libzip
  openssl
  zlib
"

# these hosts will be added to /etc/hosts as 127.0.0.1
# eg. local.mydomain.com
local_hosts+="
"

# these nodejs modules will be install using npm
nodejs_modules+="

"

# This is the ruby version that will be installed using rbenv
# the first one in the list will be set as the default. At least one
# is required to keep going with SproutWrap.
rbenv_ruby_versions=("2.3.0" "2.2.4")
