#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016 Konstantin Gredeskoul
# Project Pullulant™
# https://github.com/kigster/pullulant/
#
# Distributed under MIT License
#_______________________________________________________________________________
#
bash_it_plugins+=" ruby rbenv rvm "
bash_it_aliases+=" bundler rails "
bash_it_completions+=" rake capistrano bundler gem "
brew_packages+=" rbenv ruby-build "
brew_casks+=" rubymine webstorm "
rbenv_ruby_versions+=("2.3.0" "2.2.4")
