#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016 Konstantin Gredeskoul
# Project Pullulant™
# https://github.com/kigster/pullulant/
#
# Distributed under MIT License
#_______________________________________________________________________________
#
[[ -n "${bash_it_plugins}" ]]     || bash_it_plugins="alias-completion base git"
[[ -n "${bash_it_aliases}" ]]     || bash_it_aliases="atom git homebrew homebrew-cask npm osx vim"
[[ -n "${bash_it_completions}" ]] || bash_it_completions="brew git hub ssh"

# List of Brew Formulas to install and l`ink
[[ -n "${brew_packages}" ]] || brew_packages="
  ack
  bash
  bash-completion
  cmake
  git
  go
  haproxy
  imagemagick
  jemalloc
  jq
  libiconv
  libmemcached
  libxml2
  libxslt
  libzip
  netcat
  nginx
  nmap
  openssl
  pcre
  pstree
  qt
  rbenv
  redis
  rsync
  ruby-build
  tree
  vim
  watch
  wget
  zlib
"

[[ -n "${brew_packages_to_link_after_install}" ]] || brew_packages_to_link_after_install=""

[[ -n "${brew_casks}" ]] || brew_casks="
  atom
  homebrew/cask-versions/github-beta
  homebrew/cask-versions/docker-edge
  rowanj-gitx
  teamviewer
  macdown
"

[[ -n "${brew_relink_packages}" ]] || brew_relink_packages="
  libiconv
  libxml2
  libxslt
  libzip
  openssl
  zlib
"
# these hosts will be added to /etc/hosts as 127.0.0.1
# eg. local.mydomain.com
[[ -n "${local_hosts}" ]] || local_hosts=""

# This is the ruby/python version that will be installed using rbenv
# the first one in the list will be set as the default. At least one
# is required to keep going with SproutWrap.
[[ -n "${rbenv_ruby_versions}" ]]   || rbenv_ruby_versions=("2.6.2")
[[ -n "${rbenv_ruby_default}" ]]    || rbenv_ruby_default="2.6.2"
[[ -n "${pyenv_python_versions}" ]] || pyenv_python_versions=()

# These define optional modules for node, python and ruby. Note that
# these are installed as part of the corresponding install process.
# So python would only install if `python_install` is run.

[[ -n "${nodejs_modules}" ]] || nodejs_modules="
  bower
"
[[ -n "${python_modules}" ]] || python_modules="
"

[[ -n "${ruby_modules}" ]]   || ruby_modules="
  activesupport
  awesome_print
  aws
  colored2
  git-smart
  irbtools
  pivotal_git_scripts
  pry
  pry-doc
  rspec
  sym
  travis
  warp-dir
  rails
"

[[ -n "${alfred_plugins}" ]] || alfred_plugins="
  https://github.com/bevesce/unicode-symbols-search/raw/master/Unicode%20Symbols%20Search.alfredworkflow
  https://github.com/deanishe/alfred-stackoverflow/raw/master/StackOverflow-1.2.1.alfredworkflow
  https://github.com/packal/repository/raw/master/com.shaoshing.alfred-evernote/search_evernote.alfredworkflow
  https://github.com/packal/repository/raw/master/com.alfredapp.mdeboer.atom/atom.without.icons_.alfredworkflow
  https://github.com/packal/repository/raw/master/com.spr.translate/translate.alfredworkflow
  https://github.com/packal/repository/raw/master/wolph.unit-converter/unit_converter.alfredworkflow
  https://github.com/packal/repository/raw/master/com.fniephaus.homebrew/homebrew-for-alfred.alfredworkflow
"

[[ -n "${iterm_themes}" ]]     || iterm_themes="BirdsOfParadise Atom Desert 3024 "
