#!/usr/bin/bash env

source "${bash_files_dir}/.bash_colors"

function sep {
  printf "____________________________________________________________________________________\n" $1
}

function indented_list {
  local list="$1"
  local width="$2"
  local indent="$3"
  echo "$list" | fold -sw $width | sed -E "s/(^|$)/${indent}/g"
}

function tool_info {
  printf " ___________________________________________________________________________________\n"
  printf "|                                                                                   |\n"
  printf "|  ${txtgrn}Pullulant (or gently: 'pu')                                       ${txtrst}🌹  🌻  🍄  🦀  🎃  |\n"
  printf "|  ${txtylw}Development Environment Installer v${bldblu}$(cat VERSION).${txtwht}                                        |\n"
  printf "|  Git rev ${txtgrn}$(git log --pretty=oneline --abbrev-commit | head -1 | awk '{print $1}').${txtwht}                                                                 |\n"
  printf "|___________________________________________________________________________________|\n"
  installer_info
}

function installer_info {
  local installer_list=$(indented_list "$installers" 70 '   ')
  local helper_list=$(indented_list "$helpers"    70 '   ')
  local run_list=$(indented_list "$runners"    70 '   ')

  printf "                                                                                    \n"
  printf "Installers:\n"
  printf "${txtylw}%-68s ${txtrst}\n" "$installer_list"
  printf "                                                                                    \n"
  printf "Helpers:\n"
  printf "${txtylw}%-68s ${txtrst}\n" "$helper_list"
  if [ ! -z "$(echo $run_list | sed 's/[ \n]//g')" ]; then
    printf "                                                                                    \n"
    printf "Actual Run List:\n"
    printf "${bldylw}%-68s ${txtrst}\n" "$run_list"
  fi
}

function greet {
  tool_info
  printf "\n${txtrst}"
}

function section {
  printf "${bldblu}                             ___________________________\n"
  printf "${bldblu}____________________________|${bldwht}${bakblu} %12s %-12s ${txtrst}|____________________________${txtrst}\n\n" "installing" $1
}

function help {
  printf "Usage: ./$(basename $0) -a [-S] [-B] [-n|-q|-v]\n"
  printf "       ./$(basename $0) -r 'runner1 runner2 ...' [-S] [-B] [-n|-q|-v]\n"
  printf "       ./$(basename $0) -r homebrew [-L] [-R] [-n|-q|-v]\n"
  printf "   Or: ./$(basename $0) [-l] [-h|-H|-x]\n\n"
  printf "
Where, runner is either an installer or a helper.

  -a          run [a]ll installers in order
  -r runner   run only a specified [r]unner (either helper or installer)
  -S          [S]proutwrap is disabled during the install
  -B          [B]rew-upgrade is disabled

  -L          [L]ink or relink each brew of formulas with --force
  -R          [R]einstall each brew formula with --force

  -q          [q]uiet mode: stop printing commands before and after run.
  -v          [v]erbose run show command's output, and add -v to some
  -n          dry-ru[n] – print commands, but don't actually run them.

  -l          [l]ists available runners – helpers and installers
  -h          this [h]elp message
  -H          this help message, and explanation of helpers and installers
  -X          same as -H but in plain ascii (also saves into doc/help)

Examples:
    ./$(basename $0) -a                          # install everything
    ./$(basename $0) -r reinstall-postgres       # run just reinstall-postgres
    ./$(basename $0) -rf 'brew-wipe homebrew'    # wipe and reinstall homebrew
    ./$(basename $0) -aSB                        # install everything, minus
                                            # homebrew and sprout-wrap
"
}

function details {
  printf "
  Runner:
      Most common usage is with the ${bldlw}-a ${txtrst} flag, that runs all installers.
      Installers are bash modules located in the ${modules_dir} folder. Each
      installer has a bash function that matches the name of the file.

      The -r flag can be supplied more than once, or once but with multiple
      arguments in quotes, eg ${bldylw}-r 'runner1 runner2'${txtrst} or ${bldylw}-r runner1
      -r runner2${txtrst}. Presence of this flag indicates that only specified
      runnings will run.

  Helpers
      Helpers are similar to installers, but they are not ordered, and are
      not included in the default install. They are meant to be used ad-hoc.

      Eg, to wipe out existing PostgreSQL and re-run the installer
      do this below. This may be necessary when installing on an existing
      machine with an outdated or broken PostgreSQL:
"
}
