#!/usr/bin/env bash
function config {
  # Script-level Constants

  readonly timestamp=`date "+%Y%m%d%H%M%S"`
  readonly sprout_wrap_repo="git@github.com:pivotal-sprout/sprout-wrap.git"
  readonly install_stdout=/tmp/pullulant.stdout.$$.$timestamp
  readonly install_stderr=/tmp/pullulant.stderr.$$.$timestamp
  # folders to chmod
  readonly folders="/usr/local /var/chef /opt"
  # Path that includes rbenv and pyenv
  readonly PATH="$HOME/.rbenv/shims:$HOME/.pyenv/shims:$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  readonly LANG=en_US.UTF-8
  readonly LC_ALL=en_US.UTF-8

  readonly modules_dir=./installers
  readonly helpers_dir=./helpers
  readonly home_dir=${HOME}
  readonly backup_dir=${home_dir}/.backup/$timestamp

  # these can be overridden by the flags
  export install_only=
  export verbose=yes
  export dryrun=
  export skip_brew_upgrade=
  export skip_sprout_wrap=
  export brew_force_install=

  # these brew packages are always attempted to be upgraded, while the
  # ones in sprout-wrap are not. So here we want to list things that are
  # important to keep most recent.
  export brew_packages="
    rbenv
    ruby-build
    watch
    git
    bash
    node
    npm
    homebrew/dupes/rsync
    bash-completion
    redis
    nginx
    libxml2
    libxslt
    libiconv
    libzip
    zlib
    zsh
    openssl
    libmemcached
    vim
    wget
  "
  export local_hosts="
  "
  export nodejs_modules="
    bower
    ember-cli
  "
}
