#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016 Konstantin Gredeskoul
# Project Pullulant™
# https://github.com/kigster/pullulant/
#
# Distributed under MIT License
#_______________________________________________________________________________
#
#
function package-config {
  # Script-level Constants
  export var_pullulant_symbol_ok=${var_pullulant_symbol_ok-" ✅ "}
  export var_pullulant_symbol_error=${var_pullulant_symbol_error-" ⛔️     "}
  export var_pullulant_symbol_ignored=${var_pullulant_symbol_ignored-" 🙄   "}
  export var_zsh_theme=${var_zsh_theme-"reinvent-one"}
  export var_brew_cask_appdir=${var_brew_cask_appdir-"/Applications"}
  readonly export const_timestamp=`date "+%Y%m%d%H%M%S"`
  readonly export const_sprout_wrap_repo="https://github.com/pivotal-sprout/sprout-wrap"

  readonly export cmd_output_dir=/tmp/pullulant

  mkdir -p ${cmd_output_dir} || true

  readonly export const_cmd_stdout=${cmd_output_dir}/stdout.${const_timestamp}
  readonly export const_cmd_stderr=${cmd_output_dir}/stderr.${const_timestamp}

  touch ${const_cmd_stderr}
  touch ${const_cmd_stdout}

  readonly export const_combined_stderr=${cmd_output_dir}/combined.${const_timestamp}

  # const_owned_folder_list to chmod
  readonly export const_owned_folder_list="
    /usr/local/Caskroom
    /usr/local/Cellar
    /usr/local/Frameworks
    /usr/local/Homebrew
    /usr/local/bin
    /usr/local/etc
    /usr/local/include
    /usr/local/jamf
    /usr/local/lib
    /usr/local/opt
    /usr/local/sbin
    /usr/local/share
    /usr/local/var
    /var/chef
    /opt
    /Library/Ruby
    "

  readonly export postgresql_dir="/usr/local/var/postgres"


  if [[ -n $(which brew) ]] ; then
    declare -a pgversions=($(brew search postgresql -v | grep '@' | cut -d '@' -f 2))
  else
    declare -a pgversions=(9.5 9.4 9.6 10)
  fi

  declare -a supported_postgres_versions=(${pgversions[@]})

  # Path that includes rbenv and pyenv
  export PATH="$HOME/.rbenv/shims:$HOME/.pyenv/shims:$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  export LANG=en_US.UTF-8
  export LC_ALL=en_US.UTF-8

  readonly export supported_postgres_versions
  readonly export pu_signal_next_runner=$(kill -l SIGUSR1)
  readonly export pu_signal_interrupt=$(kill -l SIGTERM)

  readonly export home_dir=${HOME}
  readonly export pu_cfg="${home_dir}/.pu"
  readonly export backup_dir=${pu_cfg}/backups/$const_timestamp

  readonly export modules_dir=./installers
  readonly export helpers_dir=./helpers
  readonly export bash_files_dir="./files/home"
  readonly export rsync_home_dir="./files/home/"
  readonly export rsync_atom_dir="./files/atom"
  readonly export zsh_rsync_home_dir="./files/zsh/"
  readonly export custom_packages_file="${HOME}/.pu/packages"
  readonly export bash_it_home="${HOME}/.bash_it"
  readonly export service_list="nginx haproxy postgres redis memcached elastic solr mysql"
  readonly export alfred_dir="${HOME}/Desktop/Pullulant/Alfred"

  [[ -n "$(which apm)" ]] && apm=apm
  [[ -n "$(which apm-beta)" ]] && apm="apm-beta"

  # these can be overridden by the flags
  readonly export pu_options="
    opts_nokogiri_donot_use_system_libraries
    opts_install_only_selected_themes
    opts_interactive
    opts_quiet
    opts_runners
    opts_verbose
    opts_dryrun
    opts_debug
    opts_force
    opts_continue_on_runner_error
    opts_continue_on_statement_error
    opts_suppress_headers
    opts_skip_sprout_wrap
    opts_skip_brew_upgrade
    opts_brew_reinstall
    opts_brew_link_force
    opts_brew_formulae_only
    opts_brew_casks_only
    opts_brew_link_only
    opts_change_shell_to_zsh
    opts_features
    opts_postgres_version
  "

  for option in ${pu_options}; do
    eval "export ${option}="
  done

  opts_rsync_backup=" -b --suffix=~pu.bak "
  opts_features='default'

  export pu_skip_runners=""

  export skip_sudo_disable=false
}

function pu_option_value {
  option=$1
  eval "echo $"${option}
}

package-config
