#!/usr/bin/env bash
function package-config {
  # Script-level Constants
  export var_pullulant_symbol_ok=${var_pullulant_symbol_ok-" ✅ "}
  export var_pullulant_symbol_error=${var_pullulant_symbol_error-" 📛 🚫 ⛔️ 🆘 💀 💔 ❗️ "}
  export var_pullulant_symbol_ignored=${var_pullulant_symbol_ignored-" 🙄   "}
  export var_zsh_theme=${var_zsh_theme-"reinvent-one"}
  export var_brew_cask_appdir=${var_brew_cask_appdir-"/Applications"}
  readonly export const_timestamp=`date "+%Y%m%d%H%M%S"`
  readonly export const_sprout_wrap_repo="git@github.com:pivotal-sprout/sprout-wrap.git"
  readonly export const_cmd_stdout=/tmp/pullulant.stdout.$$.$const_timestamp
  readonly export const_cmd_stderr=/tmp/pullulant.stderr.$$.$const_timestamp
  # const_owned_folder_list to chmod
  readonly export const_owned_folder_list="/usr/local /var/chef /opt /Library/Caches/Homebrew"

  # Path that includes rbenv and pyenv
  export PATH="$HOME/.rbenv/shims:$HOME/.pyenv/shims:$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  export LANG=en_US.UTF-8
  export LC_ALL=en_US.UTF-8

  readonly export modules_dir=./installers
  readonly export helpers_dir=./helpers
  readonly export bash_files_dir="./files/home"
  readonly export home_dir=${HOME}
  readonly export backup_dir=${home_dir}/.backup/$const_timestamp
  readonly export rsync_home_dir="./files/home/"
  readonly export zsh_rsync_home_dir="./files/zsh/"
  readonly export custom_packages_file="${HOME}/.pullulant_packages"

  # these can be overridden by the flags
  readonly export pu_options="
    opts_quiet
    opts_runners
    opts_verbose
    opts_dryrun
    opts_skip_brew_upgrade
    opts_skip_sprout_wrap
    opts_suppress_headers
    opts_brew_reinstall
    opts_brew_force_link
    opts_brew_formulae_only
    opts_brew_casks_only
    opts_brew_link_only
    opts_brew_force
  "

  for option in ${pu_options}; do
    eval "export ${option}="
  done
}

function pu_option_value {
  option=$1
  eval "echo $"${option}
}

package-config
