#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016 Konstantin Gredeskoul
# Project Pullulant™
# https://github.com/kigster/pullulant/
#
# Distributed under MIT License
#_______________________________________________________________________________
#
#
function package-config {
  # Script-level Constants
  export var_pullulant_symbol_ok=${var_pullulant_symbol_ok-" ✅ "}
  export var_pullulant_symbol_error=${var_pullulant_symbol_error-" ⛔️     "}
  export var_pullulant_symbol_ignored=${var_pullulant_symbol_ignored-" 🙄   "}
  export var_zsh_theme=${var_zsh_theme-"reinvent-one"}
  export var_brew_cask_appdir=${var_brew_cask_appdir-"/Applications"}
  readonly export const_timestamp=`date "+%Y%m%d%H%M%S"`
  readonly export const_sprout_wrap_repo="git@github.com:pivotal-sprout/sprout-wrap.git"
  readonly export const_cmd_stdout=/tmp/pullulant.stdout.$$.$const_timestamp
  readonly export const_cmd_stderr=/tmp/pullulant.stderr.$$.$const_timestamp
  readonly export const_combined_stderr=/tmp/pullulant.stderr.$$.combined
  # const_owned_folder_list to chmod
  readonly export const_owned_folder_list="
    /usr/local/Cellar
    /usr/local/bin
    /usr/local/opt
    /usr/local/lib
    /usr/local/share
    /usr/local/include
    /var/chef
    /opt
    /Library/Caches/Homebrew"
  readonly export postgresql_dir="/usr/local/var/postgres"

  # Path that includes rbenv and pyenv
  export PATH="$HOME/.rbenv/shims:$HOME/.pyenv/shims:$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  export LANG=en_US.UTF-8
  export LC_ALL=en_US.UTF-8

  readonly export home_dir=${HOME}
  readonly export modules_dir=./installers
  readonly export helpers_dir=./helpers
  readonly export backup_dir=${home_dir}/.backup/$const_timestamp
  readonly export bash_files_dir="./files/home"
  readonly export rsync_home_dir="./files/home/"
  readonly export rsync_atom_dir="./files/atom/"
  readonly export zsh_rsync_home_dir="./files/zsh/"
  readonly export custom_packages_file="${HOME}/.pullulant_packages"
  readonly export bash_it_home="${HOME}/.bash_it"
  readonly export service_list="nginx haproxy postgres redis memcached elastic solr mysql"

  [[ -n "$(which apm)" ]] && apm=apm
  [[ -n "$(which apm-beta)" ]] && apm="apm-beta"

  # these can be overridden by the flags
  readonly export pu_options="
    opts_quiet
    opts_runners
    opts_verbose
    opts_dryrun
    opts_force
    opts_continue_on_runner_error
    opts_continue_on_statement_error
    opts_suppress_headers
    opts_skip_sprout_wrap
    opts_skip_brew_upgrade
    opts_brew_reinstall
    opts_brew_link_force
    opts_brew_formulae_only
    opts_brew_casks_only
    opts_brew_link_only
    opts_change_shell_to_zsh
    opts_features
  "

  for option in ${pu_options}; do
    eval "export ${option}="
  done

  opts_rsync_backup=" -b --suffix=~pullulant-backup "
  opts_features='default'
}

function pu_option_value {
  option=$1
  eval "echo $"${option}
}

package-config
