#!/usr/bin/env bash
function pu-features {
  ls features
}

function pu-list-components {

  local name=$1
  shift
  local color=$1
  shift

  bgcolor="bak${color}"  && bgcolor=${!bgcolor}
  bldcolor="bld${color}" && bldcolor=${!bldcolor}
  fgcolor="txt${color}"  && fgcolor=${!fgcolor}

  declare -a components=("$*")
  local spacer="                       "
  printf "   ${txtwht}${fgcolor}${name}${txtrst}:\n"
  for component in "${components[@]}"; do
    printf "${spacer}${fgcolor} ● ${txtblk}${bgcolor} %-30s ${fgcolor} ● ${txtrst}\n" ${component}
  done
}

function package-config {
  declare -a features=(default ${opts_features})
  printf "\n"

  for feature in "${features[@]}"; do
    local feature_with_path=$(echo $feature | grep  '/')
    if [ "${feature_with_path}" != "${feature}" ]; then
      package_file="${pu_home}/features/${feature}/packages"
    else
      package_file="$feature"
    fi
    if [ -s "${package_file}" ]; then
      source ${package_file}
    else
      printf "${bldred}ERROR: Unable to find feature ${feature}: ${bldwht}${package_file} does not exist?${txtrst}\n\n" >&2
      abort 131
    fi
  done

  pu-list-components "Features" "grn"  "${features[@]}"
  pu-list-components "Runners"  "ylw"  "${runners[@]}"

  source "${pu_home}/lib/pu-uniq-packages"

  if [[ -n "${opts_interactive}" ]]; then
    printf "\n${txtwht}   ${undylw}Attention:${txtrst} Please review the run parameters above.\n   If something is wrong or missing, hit Ctrl-C to abort.\n\n"
    if [ -t 0 ]; then stty -echo -icanon -icrnl time 0 min 0; fi
    keypress=''
    for wait in {20..1}; do
      keypress="`cat -v`"
      printf "\033[1000D\033[0C  You have ${bakred} ${wait} ${txtrst} seconds until start. ${bldgrn} Press ANY key to continue.${txtrst}"
      sleep 1
      keypress="`cat -v`"
      if [ "x$keypress" != "x" ]; then
        echo
        break
      fi
    done
    if [ -t 0 ]; then stty sane; fi
    clear
  fi
}
