#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#
function package-config {

  [[ -s "${custom_packages_file}" ]] && {
    source "${custom_packages_file}"
  }

  # List of Brew Formulas to install and link
  [[ -n "${brew_packages}" ]] || export brew_packages="
    rbenv
    ruby-build
    watch
    git
    bash
    node
    npm
    homebrew/dupes/rsync
    bash-completion
    redis
    nginx
    libxml2
    libxslt
    libiconv
    libzip
    zlib
    zsh
    openssl
    libmemcached
    vim
    wget
    htop
    pcre
    nmap
    hub
    ack
    haproxy
    elasticsearch
    qt
    the_silver_searcher
    imagemagick
    pstree
    tree
    pyenv
    awscli
    awsebcli
    aws-as
    aws-cloudsearch
    aws-elasticbeanstalk
    aws-elasticache
    aws-mon
    jq
    cmake
    tmux
  "

    [[ -n "${brew_casks}" ]] || export brew_casks="
    clion
    webstorm
    rubymine
    shiftit
    istat-menus
    iterm2
    slack
    gitx
    google-chrome
    google-drive
    google-hangouts
    atom
    virtualbox
    slack
    dockertoolbox
    docker
    docker-compose
    kitematic
    java
    teamviewer
  "

    [[ -n "${brew_relink_packages}" ]] || export brew_relink_packages="
    libxml2
    libxslt
    libiconv
    libzip
    zlib
    openssl
  "

  # these hosts will be added to /etc/hosts as 127.0.0.1
  export local_hosts="
  "

  # these nodejs modules will be install using npm
  [[ -n "${nodejs_modules}" ]] || export nodejs_modules="
    bower
    ember-cli
  "

  # This is the ruby version that will be installed using rbenv
  # the first one is the default
  [[ -n "${rbenv_ruby_versions[@]}" ]] ||rbenv_ruby_versions=("2.3.0" "2.2.3")
}

package-config
