#!/usr/bin/env bash

# Usage: pu-trap-signals-reset INT TERM ....
pu-trap-signals-reset() {
  for sig ; do
      trap - "$sig"
  done
}

# Usage: pu-trap-signals 'expression or bash function' signal1 signal2 ..
# Bash functions will receive signal as a parameter when called through this trap.
pu-trap-signals() {
  func="$1" ; shift
  for sig ; do
    current_trap=$(trap | grep -i "sig$sig" | awk '{print $3}')
    if [[ -z "${current_trap}" ]]; then
      trap "$func $sig" "$sig"
    else
      declare -a command=($(trap | grep -i "sig$sig"| tr '\n' ' '))
      printf "Signal ${txtred}$sig${txtrst} appears to be already trapped by: [${command[*]}]\n"
    fi
  done
}
