#!/usr/bin/env bash
# List of Brew Formulas to install and l`ink
[[ -n "${brew_packages}" ]] || brew_packages="
  watch
  git
  bash
  node
  homebrew/dupes/rsync
  bash-completion
  libxml2
  libxslt
  libiconv
  libzip
  zlib
  zsh
  openssl
  vim
  wget
  htop
  pcre
  nmap
  hub
  ack
  qt
  the_silver_searcher
  imagemagick
  pstree
  tree
  awscli
  awsebcli
  aws-as
  aws-cloudsearch
  aws-elasticbeanstalk
  aws-elasticache
  aws-mon
  jq
  cmake
  tmux
  ansiweather
  go
"

[[ -n "${brew_casks}" ]] || brew_casks="
  shiftit
  istat-menus
  iterm2
  slack
  gitx
  github-desktop
  google-chrome
  google-drive
  google-hangouts
  atom-beta
  slack
  java
  teamviewer
  alfred
"

[[ -n "${brew_relink_packages}" ]] || brew_relink_packages="
  libxml2
  libxslt
  libiconv
  libzip
  zlib
  openssl
"

# these hosts will be added to /etc/hosts as 127.0.0.1
# eg. local.mydomain.com
[[ -n "${local_hosts}" ]] || local_hosts="
"

# these nodejs modules will be install using npm
[[ -n "${nodejs_modules}" ]] || nodejs_modules="
  bower
  ember-cli
"

# This is the ruby version that will be installed using rbenv
# the first one in the list will be set as the default. At least one
# is required to keep going with SproutWrap.
[[ -n "${rbenv_ruby_versions}" ]] || rbenv_ruby_versions=("2.3.0")
