#!/usr/bin/env bash

permissions() {
  local tmpfile=/tmp/sudo.${USER}
  printf "If asked, please provide your SUDO password:\n"
  run "sudo echo"  # give me sudo!
  my_group=`id -gn`  # find the primary group of the current user
  for dir in ${folders}; do
    if [ ! -d "${dir}" ]; then
      run "sudo mkdir -p ${dir}"
    fi
    run "sudo chown -R ${USER}:${my_group} ${dir}"
    run "sudo chmod -R u=xwr,g=wrx,o= ${dir}"
  done
  if [ -z "`ps -ef | grep [p]ostgresql`" -a -d "/usr/local/var/postgres" ]; then
    run "mv /usr/local/var/postgres /usr/local/var/postgres-backup.$$"
  fi
}
