#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________

permissions() {
  run "xcode-select --install 2>/dev/null; true"

  local tmpfile=/tmp/sudo.${USER}
  printf "If asked, please provide your SUDO password:\n"
  run "sudo echo"  # give me sudo!
  my_group=`id -gn`  # find the primary group of the current user
  for dir in ${const_owned_folder_list}; do
    if [ ! -d "${dir}" ]; then
      run "sudo mkdir ${opts_verbose} -p ${dir}"
    fi
    run "sudo chown -R ${USER}:${my_group} ${dir}"
    run "sudo chmod -R u=xwr,g=wrx,o= ${dir}"
  done
}
