#!/usr/bin/env bash
# This is a minimal home brew install in order to get a recent working ruby
# so that we can run sprout-wrap that contains the rest of the install.

function homebrew {
  brew=`which brew 2>/dev/null`
  if [ -z "${brew}" ]; then
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install > /tmp/brew.rb
    run 'printf "Installing Homebrew from scratch, this is so exciting!...\n"'
    run "ruby < /tmp/brew.rb"
  else
    cmd='echo "Homebrew is already installed – version: $(brew --version)"'
    run "$cmd"
    brew-update
  fi

  # Let's run this damn upgrade
  brew-upgrade

  # Let's install that goddamn brew-cask
  run "brew tap caskroom/cask" "true"

  for package in $brew_packages; do
    if [ -n "$(echo $package | grep cask)" ]; then
      brew_cask_install $package
    else
      brew_install $package
    fi
  done
  for package in $brew_relink_packages; do
    brew_relink $package
  done


  result=$(which gsed)
  status=$?
  if [ $status -ne 0 ]; then
    run "brew install gnu-sed"
    run "ln -nfs /usr/local/bin/gsed /usr/local/bin/sed"
  fi
  status=$?
}

function brew_relink {
  pkg=${1}
  run "brew unlink ${opts_verbose} $pkg --force"
  run "brew link   ${opts_verbose} $pkg --force"
}

function brew_cask_install {
  package=$1
  run "brew cask install ${package} --force --appdir=/Applications"
}

function brew_install {
  package=$1
  if [ ! -z "${opts_brew_force_reinstall}" ]; then
    run "brew uninstall ${opts_verbose} $package --force" "true"
    run "brew unlink    ${opts_verbose} $package --force" "true"
    run "brew install   ${opts_verbose} $package --force  2>&1 #show-stdout" "true"
    run "brew link      ${opts_verbose} $package --force 2>&1  #show-stdout" "true"
  else
    cmd=$(brew list $package 2>/dev/null)
    result=$?
    if [ "$result" -ne 0 ]; then
      run "brew install ${opts_verbose} $package"
    else
      run "brew upgrade ${opts_verbose} $package" "true"
    fi
    [[ -z "${opts_brew_force_link}" ]] || brew_relink ${package}
  fi
}
