#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________

export rubyinstall_ran=
function ruby_install {
  [[ -n "${rubyinstall_ran}" ]] && return
  run "echo Verifying that the ruby versions ${rbenv_ruby_versions[*]} are installed"
  for rbenv_ruby_version in ${rbenv_ruby_versions[@]}; do
    status=$(rbenv versions | grep ${rbenv_ruby_version})
    if [ $? -ne 0 ]; then
      run 'printf "${bldylw}Installing ruby from sources, this make take 2-3 minutes (get a faster box!)....${txtrst}\n"'
      run "rbenv install ${opts_verbose} ${rbenv_ruby_version}"
      run "eval $(rbenv init -) && rbenv rehash"
      [[ "$(gem list -i bundler)" == "false" ]] && run "gem install bundler"
      export PATH="$HOME/.rbenv/shims:$HOME/.pyenv/shims:$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    fi
  done

  run "rbenv global ${rbenv_ruby_versions[0]}"
  export rubyinstall_ran=yes
}
