#!/usr/bin/env bash

function zsh {
  run "rsync -a --ignore-existing ${rsync_home_dir}.zshrc ${HOME}/"
  run "rsync -a --ignore-existing ${rsync_home_dir}.select-prompt ${HOME}/"

  #run 'sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'
  oh-my-zsh-installer
  rc=${HOME}/.zshrc
  [[ -n "$(echo $SHELL | grep zsh)" ]]               || run "chsh -s $(which zsh)"
  [[ -n "$(grep THEME=\"${var_zsh_theme}\" $rc)" ]]  || run "sed -i 's/ZSH_THEME=\".*\"/ZSH_THEME=\"${var_zsh_theme}\"/g' $rc"
  [[ -n "$(grep shell-aliases $rc)" ]]               || echo "source ~/.shell-aliases" >> $rc
  [[ -n "$(grep 'rbenv init' $rc)" ]]                || echo 'eval "$(rbenv init -)"' >> $rc
}

function oh-my-zsh-installer {
  [[ -z "$(grep -e /zsh$ /etc/shells)" ]] && brew_install "zsh"
  [[ -z "$ZSH" ]]                         && ZSH=${HOME}/.oh-my-zsh
  [[ -z "$(which git)" ]]                 && brew_install "git"
  if [ -d "$ZSH" ]; then
    run "printf \"${bldylw}Looks like your oh-my-zsh is already installed\n\""
    run "printf \"${txtrst}You'll need to remove $ZSH if you want to re-install\n\""
  else
    run "env git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git $ZSH"
  fi
}
