#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#
function zsh_install {
  zsh-permissions

  rsync_opts=""

  [[ -n "${opts_force}" ]] && run "rm -rf ${HOME}/.oh-my-zsh ${HOME}/.zsh* ${HOME}/.zcomp*"

  #run 'sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'
  oh-my-zsh-installer

  [[ -z "$(echo $SHELL | grep zsh)" && -z "${opts_dont_change_shell}" ]] && run "chsh -s /usr/local/bin/zsh"

  run "rsync -a ${zsh_rsync_home_dir}.zshrc ${HOME}/"
  run "rsync -a ${zsh_rsync_home_dir}.select-prompt ${HOME}/"
  run "rsync -a ${zsh_rsync_home_dir}.oh-my-zsh/ ${HOME}/.oh-my-zsh"

  rc=${HOME}/.zshrc
  [[ -n "$(grep THEME=\"${var_zsh_theme}\" $rc)" ]]  || run "sed -i '' -e 's/ZSH_THEME=\".*\"/ZSH_THEME=\"${var_zsh_theme}\"/g' $rc"
  [[ -n "$(grep PU_HOME $rc)" ]] || run "echo 'PU_HOME=${pu_home}; PATH=\$PATH:\${PU_HOME}; unalias pu' >> $rc "
}

function oh-my-zsh-installer {
  [[ -z "$(grep -e /zsh$ /etc/shells)" ]] && brew_install "zsh"
  [[ -z "$ZSH" ]]                         && ZSH=${HOME}/.oh-my-zsh
  [[ -z "$(which git)" ]]                 && brew_install "git"
  if [ -d "$ZSH" ]; then
    run "printf \"${bldylw}Looks like your oh-my-zsh is already installed\n\""
    run "printf \"${txtrst}You'll need to remove $ZSH if you want to re-install\n\""
  else
    run "env git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git $ZSH"
  fi
}

function zsh-permissions {
  run "chmod -R 750 /usr/local/share/zsh"
  run "chmod -R 750 /usr/local/Cellar/zsh"
}
