#!/usr/bin/env bash

function bash {
    run "pwd"
    files=`cd ${bash_files_dir} && ls -1 .[a-zA-Z]* && cd - >/dev/null`
    mkdir -p ${backup_dir}
    for file in ${files}; do
      if [ -f "${home_dir}/${file}" ]; then
        # echo "overwriting ${home_dir}/${file} (backing up existing file to ${backup}/${file}.${const_timestamp})"
        run "mv ${home_dir}/${file} ${backup_dir}/${file}"
      else
        echo "installing ${home_dir}/${file}"
      fi
      run "cp -v ${bash_files_dir}/$file $home_dir"
    done
    ln -nfs ~/.bashrc ~/.bash_login
    $(grep bashrc ~/.bash_profile > /dev/null)
    if [ $? -eq 1 ]; then
      run "echo 'appending ~/.bashrc to .bash_profile...'"
      run "echo 'source ~/.bashrc' >> ~/.bash_profile"
    fi
}
