#!/usr/bin/env bash
function preferences {
  cleanup_prefs
  run "cp -prf ./files/library-preferences/*  ${HOME}/Library/Preferences"
}

function cleanup_prefs {
  run "rm -rf '${HOME}/Library/Saved Application State/com.googlecode.iterm2.savedState'"
  run "rm -rf '${HOME}/Library/Caches/com.googlecode.iterm2'"
  run "rm -rf '${HOME}/Preferences/com.googlecode.iterm2.plist'"
}
