#!/usr/bin/env bash
function preferences {
    run "rm -rf '${HOME}/Library/Saved Application State/com.googlecode.iterm2.savedState'"
    run "rm -rf '${HOME}/Library/Caches/com.googlecode.iterm2'"
    run "rm -rf '${HOME}/Preferences/com.googlecode.iterm2.plist'"
    run "cp -prf ./files/library-preferences/*  ${HOME}/Library/Preferences"
}
