#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#
function bash_install {
  run "rsync -a ${rsync_home_dir} ${HOME}"

  ln -nfs ~/.bashrc ~/.bash_login
  $(grep bashrc ~/.bash_profile > /dev/null)
  if [ $? -eq 1 ]; then
    run "echo 'appending sourcing of ~/.bashrc to .bash_profile...'"
    run "echo 'source ~/.bashrc' >> ~/.bash_profile"
  fi
  local rc="${HOME}/.bashrc"
  [[ -n "$(grep PU_HOME $rc)" ]] || run "echo 'PU_HOME=${pu_home}; PATH=\$PATH:\${PU_HOME}; unalias pu 2>/dev/null' >> $rc "
}
