#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#

function atom {
  status=0
  run "rsync -a ${rsync_atom_dir} ${HOME}/.atom"
  if [ -z "$apm" ]; then
    run "printf \"${bldylw} It looks like you don't have *apm* installed – it comes with Atom.\n\""
    run "printf \"${bldwht} Please make sure you have the latest Atom installed, then re-run\n"
  else
    run "$apm install  --packages-file ${HOME}/.atom/packages.txt # show-stdout"
  fi
  return $status
}
