#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016 Konstantin Gredeskoul
# Project Pullulant™
# https://github.com/kigster/pullulant/
#
# Distributed under MIT License
#_______________________________________________________________________________

function install_python_modules {
  python_sudo=""
  [[ "$(pyenv versions | grep '*' | awk '{print $2}')" == 'system' ]] && python_sudo='sudo '
  for module in ${python_modules}; do
    run "${python_sudo}pip install $(echo \"${module}\" | tr '\n' ' ')"
  done
}

export pythoninstall_ran=
function install_python {
  [[ -n "${pythoninstall_ran}" ]] && return
  run "echo Verifying that the python versions ${pyenv_python_versions[*]} are installed"
  for pyenv_python_version in ${pyenv_python_versions[@]}; do
    last_command_status=$(pyenv versions | grep ${pyenv_python_version})
    if [ $? -ne 0 ]; then
      run 'printf "${bldylw}Installing python from sources, this make take 2-3 minutes (get a faster box!)....${txtrst}\n"'
      run "pyenv install ${opts_verbose} ${pyenv_python_version}"
      run "eval $(pyenv init -) && pyenv rehash"
      export PATH="$HOME/.pyenv/shims:$HOME/.pyenv/shims:$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    fi
    run "pyenv global ${pyenv_python_version}"
    run "pip install --upgrade pip"
    install_python_modules
  done
  run "pyenv global ${pyenv_python_versions[0]}"
  export pythoninstall_ran=yes
}
