#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________

function install_ruby_modules {
  [[ -n "${ruby_modules}" ]] && {
    for gem in ${ruby_modules}; do
      run "gem install --no-ri --no-rdoc $gem"
    done
  }
}

export rubyinstall_ran=
function install_ruby {
  [[ -n "${rubyinstall_ran}" ]] && return
  run "echo Verifying that the ruby versions ${rbenv_ruby_versions[*]} are installed"
  local default_ruby=${rbenv_ruby_versions[0]}
  for rbenv_ruby_version in ${rbenv_ruby_versions[@]}; do
    last_command_status=$(rbenv versions | grep ${rbenv_ruby_version})
    if [ $? -ne 0 ]; then
      run 'printf "${bldylw}Installing ruby from sources, this make take 2-3 minutes (get a faster box!)....${txtrst}\n"'
      run "rbenv install ${opts_verbose} ${rbenv_ruby_version}"
      run "eval $(rbenv init -) && rbenv rehash"
      run "hash -r"
      [[ "$(gem list -i bundler)" == "false" ]] && run "gem install bundler --no-ri --no-rdoc"
      export PATH="$HOME/.rbenv/shims:$HOME/.pyenv/shims:$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    fi
    install_ruby_modules
  done

  run "rbenv global ${default_ruby}"
  export rubyinstall_ran=yes
}
