#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
# File: pu-completion
#_______________________________________________________________________________
#
function install_bash_dotfiles() {
  run "rsync ${opts_rsync_backup} -v -a ${rsync_home_dir} ${HOME} # show-stdout "
  ln -nfs ~/.bashrc ~/.bash_login
  local rc="${HOME}/.bash_pullulant"
  touch $rc
  [[ -z "$(grep PU_HOME $rc)" ]]         && run "echo 'PU_HOME=${pu_home}; PATH=\$PATH:\${PU_HOME}' >> $rc # show-stdout"
  [[ -z "$(grep 'pu-completion' $rc)" ]] && run "cat ${pu_home}/bin/pu-completion >> $rc # show-stdout"
  [[ -z "$(grep pullulant ${HOME}/.gitconfig 2>/dev/null )" ]] && {
    touch ${HOME}/.gitconfig
    echo "
[include]
    path = ${HOME}/.gitconfig-pullulant
"   >> ${HOME}/.gitconfig
  }
}

# shortcut
function _bash {
  bash_install
}
