#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#

function install_osx_tweaks() {
  # stop forced authentication for os-x updates
  # run "sudo defaults delete /Library/Preferences/com.apple.SoftwareUpdate CatalogURL"
  run "sudo ln -nfs /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport /usr/local/bin/airport"
  printf "${bldgrn}You should now be able to run command ${bldwht}airport -s${bldgrn} to can local wifi networks\n"

  run "rsync ${opts_verbose} ${opts_rsync_backup} -a files/applications /Applications"
}
