#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#

function install_rubymine_settings() {
  run "sudo chown -R ${USER} /Applications/RubyMine*"
  run "rsync ${opts_verbose} ${opts_rsync_backup} -rltgoDv --no-perms files/applications/** /Applications # show-stdout"
}
