#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#

function rubymine() {
  run "sudo chown -R ${USER} /Applications/RubyMine*"

  update_application "/Applications/RubyMine.app"
  update_application "/Applications/RubyMine EAP.app"
}

function update_application() {
  app=$*

  if [[ -d "$*" ]]; then 
    run "rsync ${opts_verbose} ${opts_rsync_backup} -rltgoDv --no-perms './files${app}/' '${app}/' # show-stdout"
  fi
 }
