#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#
function prefs {
  cleanup_prefs
  run "cp -prf ./files/library-preferences/*  ${HOME}/Library/Preferences"
  run "cp  ./files/library-preferences/com.googlecode.iterm2.plist  ${HOME}/Documents"
  last_command_status=$?
  return $last_command_status
}

function cleanup_prefs {
  run "mkdir -p $backup_dir"
  run "rm -f '${HOME}/Library/Saved Application State/com.googlecode.iterm2.savedState'"
  run "rm -f '${HOME}/Library/Caches/com.googlecode.iterm2'"
  run "rm -f '${HOME}/Preferences/com.googlecode.iterm2.plist'"
}
