#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#
function prefs {
  cleanup_prefs
  run "cp -prf ./files/library-preferences/*  ${HOME}/Library/Preferences"
}

function cleanup_prefs {
  run "mkdir -p $backup_dir"
  run "mv '${HOME}/Library/Saved Application State/com.googlecode.iterm2.savedState' ${backup_dir}"
  run "mv '${HOME}/Library/Caches/com.googlecode.iterm2' ${backup_dir}"
  run "mv '${HOME}/Preferences/com.googlecode.iterm2.plist' ${backup_dir}"
}
