#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#

function atom() {
  last_command_status=0

  if [[ -d "${HOME}/.atom" && -z "${opts_force}" ]]; then
    [[ -n "$apm" ]] && run "$apm update"
    # create a backup
    run "tar cvzf '${HOME}/.atom.tarz' '${HOME}/.atom'"
  fi

  run "rsync -a -u ${rsync_atom_dir}/ ${HOME}/.atom"

  if [ -z "$apm" ]; then
    run "printf \"${bldylw} It looks like you don't have *apm* installed – it comes with Atom.\n\""
    run "printf \"${bldwht} Please make sure you have the latest Atom installed, then re-run\n"
  else
    run "$apm install  --packages-file ${HOME}/.atom/packages.txt # show-stdout"
  fi

  return $last_command_status
}
