#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016-2021 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#
function install-vim() {
  #run "rsync ${opts_rsync_backup} -v --perms -a ./files/home/{HOME} # show-stdout "
  cp -rnpv files/home/.vim* ${HOME}

  # Install all plugins
  vim +PlugInstall +qall
}
