#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#
function install-vim {
  run "mkdir -p ${HOME}/.vim"
  run "sudo chown -R ${USER} ${HOME}/.vim"
  run "rsync ${opts_rsync_backup} -v --perms -a ./files/vim/ ${HOME} # show-stdout "
  run "[[ -f ~/.vimrc ]] && mv ~/.vimrc ~/.vimrc.~bak"
  run "cp files/home/.vimrc ${HOME}"
}
