#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#
function pu_vim {
  #run "rsync ${opts_rsync_backup} -v --perms -a ./files/home/{HOME} # show-stdout "
  cp -rnpv files/home/.vim* ${HOME}
}
