#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#

function pu_cleanup_prefs {
  run "mkdir -p $backup_dir"
}

function install-osx() {
  # stop forced authentication for os-x updates
  run "sudo defaults delete /Library/Preferences/com.apple.SoftwareUpdate CatalogURL; true"
  run "sudo ln -nfs /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport /usr/local/bin/airport"
  printf "${bldgrn}You should now be able to run command ${bldwht}airport -s${bldgrn} to can local wifi networks\n"

  cleanup_prefs

  run "cp -prf ./files/library-preferences/*  ${HOME}/Library/Preferences"
  last_command_status=$?
  return $last_command_status
}
