#!/usr/bin/env bash
#_______________________________________________________________________________
#
# (c) 2016 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#
function install-postgresql() {
  postgres-permissions
  postgres-install
}

function install-postgres() {
  install-postgresql "$@"
}
