#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016-2021 Konstantin Gredeskoul
# https://github.com/kigster
#
# For project Pullulant
# https://github.com/kigster/pullulant/
#
# MIT License
#_______________________________________________________________________________
#

function install-etchosts() {
    for hostname in $local_hosts; do
        add_hostname $hostname
    done
    export last_command_status=0
    return $last_command_status
}

function add_hostname {
    sudo-enable
    hostname="$1"
    result=$(grep $hostname /etc/hosts)
    if [ $? -ne 0 ]; then
        run "echo 127.0.0.1 $hostname | sudo tee -a /etc/hosts > /dev/null"
    else
        run "echo already have $hostname in /etc/hosts"
    fi
}
