#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016 Konstantin Gredeskoul
# Project Pullulant™
# https://github.com/kigster/pullulant/
#
# Distributed under MIT License
#_______________________________________________________________________________
#
bash_it_plugins+="
  pyenv python
"

# List of Brew Formulas to install and l`ink
brew_packages+="
  pyenv
"

brew_casks+="
  pycharm
  webstorm
  atom-beta
  textmate
"

brew_relink_packages+="
  libiconv
  libxml2
  libxslt
  libzip
  openssl
  zlib
"

# these hosts will be added to /etc/hosts as 127.0.0.1
# eg. local.mydomain.com
local_hosts+=""

# these nodejs modules will be install using npm
nodejs_modules+=""

pyenv_python_versions=("2.7.11")
