#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016 Konstantin Gredeskoul
# Project Pullulant™
# https://github.com/kigster/pullulant/
#
# Distributed under MIT License
#_______________________________________________________________________________
#
bash_it_plugins+=" pyenv python "
brew_packages+=" pyenv "
brew_casks+=" pycharm webstorm "
brew_relink_packages+=" libmemcached "
python_modules+="
  requests
  nose
  spec
  scapy
"

pyenv_python_versions=("2.7.11")
