#!/usr/bin/env bash
#_______________________________________________________________________________
#
# © 2016 Konstantin Gredeskoul
# Project Pullulant™
# https://github.com/kigster/pullulant/
#
# Distributed under MIT License
#_______________________________________________________________________________
#
bash_it_plugins+="javascript node nvm"
bash_it_aliases+="npm"
bash_it_completions+="npm"
brew_packages+=" node npm  "
brew_casks+=" webstorm "
nodejs_modules+=" bower ember-cli "
